CREATE TABLE IF NOT EXISTS game_data (
    id SERIAL PRIMARY KEY NOT NULL,
    game_id TEXT NOT NULL,
    summoner_name TEXT NOT NULL,
    champion_name TEXT NOT NULL,
    lane TEXT NOT NULL,
    kills INTEGER NOT NULL,
    deaths INTEGER NOT NULL,
    assists INTEGER NOT NULL,
    gold_earned INTEGER NOT NULL,
    total_damage INTEGER NOT NULL,
    tower_damage INTEGER NOT NULL,
    pentakills INTEGER NOT NULL,
    total_damage_taken INTEGER NOT NULL,
    dragon_kills INTEGER NOT NULL,
    baron_kills INTEGER NOT NULL,
    tower_kills INTEGER NOT NULL,
    total_teammate_heals INTEGER NOT NULL,
    vision_score INTEGER NOT NULL,
    wards_placed INTEGER NOT NULL,
    wards_killed INTEGER NOT NULL,
    kill_participation DOUBLE PRECISION NOT NULL,
    scuttle_crab_kills INTEGER NOT NULL,
    total_time_cc_dealt INTEGER NOT NULL,
    total_minions_killed INTEGER NOT NULL,
    inhibitors_killed INTEGER NOT NULL
);