POST http://localhost:8080/api/player
Content-Type: application/json
Accept: application/json

{
  "puuid": "L-8nPd33SToj8rLm6ejfyxIZPS1LA5t9EmOjPL1VOABlaV-miO2ChGXcZlFDm1yroH4_Hs_JlOIpCw",
  "summonerId": "vhWPSrU2-eT0XdnmQp_-qyYSaG6oZqlALjFcsAMdQZbMU7Q",
  "summonerName": "BrittanySPEARS",
  "team": "Cucks Anonymous"
}