POST http://localhost:8080/api/player
Content-Type: application/json
Accept: application/json

{
  "summonerName": "yummi cupkeki",
  "team": "Feet Finders",
  "tagline": "9690",
  "rank": "",
  "level": ""
}

###

POST http://localhost:8080/api/player
Content-Type: application/json
Accept: application/json

{
  "summonerName": "SheriffSoco",
  "team": "Feet Finders",
  "tagline": "0765",
  "rank": "",
  "level": ""
}

###

POST http://localhost:8080/api/player
Content-Type: application/json
Accept: application/json

{
  "summonerName": "SphincterDink",
  "team": "Feet Finders",
  "tagline": "NA1"
}

###

POST http://localhost:8080/api/player
Content-Type: application/json
Accept: application/json

{
  "summonerName": "Big Poop",
  "team": "Feet Finders",
  "tagline": "NA1"
}

###

POST http://localhost:8080/api/player
Content-Type: application/json
Accept: application/json

{
  "summonerName": "TheBigHook",
  "team": "Feet Finders",
  "tagline": "NA1"
}

###

POST http://localhost:8080/api/player
Content-Type: application/json
Accept: application/json

{
"summonerName": "sara tohnin",
"team": "Feet Finders",
"tagline": "NA1"
}