POST http://localhost:8080/api/player
Content-Type: application/json
Accept: application/json

{
  "summonerName": "BrittanySPEARS",
  "team": "Ornn",
  "tagline": "NA1"
}

###

POST http://localhost:8080/api/player
Content-Type: application/json
Accept: application/json

{
  "summonerName": "Fazrawdes",
  "team": "Ornn",
  "tagline": "NA1"
}

###

POST http://localhost:8080/api/player
Content-Type: application/json
Accept: application/json

{
  "summonerName": "KiwoP",
  "team": "Ornn",
  "tagline": "NA1"
}

###

POST http://localhost:8080/api/player
Content-Type: application/json
Accept: application/json

{
  "summonerName": "Sloppy",
  "team": "Ornn",
  "tagline": "NA1"
}